name: Azure Web App Container Deployment

 

on:
  push:
    branches:
      - feature_1  # Change this to your default branch

 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

 

      # - name: Skip TEST Maven
      #   run: mvn install -Dmaven.test.skip=true

 

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker
        uses: azure/docker-login@v1
        with:
          login-server: https://hub.docker.com/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

 

      # - name: Build and push Docker image
      #   run: |
      #     docker build -t himanshitiwari/shell-java-app:0.0.1.Release .
      #     docker push himanshitiwari/shell-java-app:0.0.1.Release

 

      - name: Build Docker Image
        run: docker build -t swetank001/shell-java-app:0.0.1.Release .

 

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push swetank001/shell-java-app:0.0.1.Release

 

      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     app-name: azure-web-app-shell-java-app
      #     images: panda101101/shell-java-app:0.0.1.Release
